### ISSUE TITLE
would recommend creating a small screencast that captures plugin in action

### ISSUE THREAD

**Issue by soodoku** [AlexLamson/DataWrangler#16]
For instance,
https://github.com/recite/re-cite.org/

The plugin seems useful, btw.

**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AlexLamson** [comment]
Screencast added in commit ebdd2c32022e3f4f27a1cf50af9b902782b7e90a

**Comment by soodoku** [comment]
Nicely done!
